services:
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
      - nginx

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=mydb
    volumes:
      - db_data:/var/lib/mysql
  nginx:
    image: nginx:alpine
    ports:
      - "1235:1235"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./sona-nyl.cn.pem:/etc/nginx/ssl/sona-nyl.cn.pem
      - ./sona-nyl.cn.key:/etc/nginx/ssl/sona-nyl.cn.key
    depends_on:
      - app
    restart: unless-stopped
volumes:
  db_data: